name: Deploy Streamlit App to Azure

# Triggers the workflow on push or pull request to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code from the repository
      - name: 'Checkout code'
        uses: actions/checkout@v2

      # Step 2: Set up Python 3.9 (or the version your app needs)
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install Python dependencies (from requirements.txt)
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional Step: Run tests (if you have tests defined)
      # Uncomment the next lines if you have tests.
      #- name: 'Run tests'
      #  run: |
      #    pytest

      # Step 4: Deploy to Azure Web App using Azure Web Apps Deploy GitHub Action
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}  # Azure Web App name
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}  # Service Principal credentials
          slot-name: 'production'  # Optional: specify a slot if using slots

      # Step 5: Print deployment message
      - name: 'Deployment complete'
        run: echo "Streamlit app deployed successfully!"
