name: Deploy Streamlit App to Azure

# Triggers the workflow on push or pull request to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code from the repository
      - name: 'Checkout code'
        uses: actions/checkout@v2

      # Step 2: Set up Python 3.11 (for Streamlit)
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      # Step 3: Install Python dependencies (from requirements.txt)
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Login to Azure using the service principal
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 5: Deploy to Azure Web App using Azure CLI
      - name: 'Deploy to Azure Web App'
        run: |
          az webapp up --name ${{ secrets.AZURE_WEBAPP_NAME }} \
                       --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
                       --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
                       --runtime "PYTHON:3.11"

      # Step 6: Print deployment message
      - name: 'Deployment complete'
        run: echo "Streamlit app deployed successfully!"
